// Mocks generated by Mockito 5.0.11 from annotations
// in flutter_clean_arch/test/feature/auth/domain/repository/do_login_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_clean_arch/features/data/datasources/do_login_data_source.dart'
    as _i3;
import 'package:flutter_clean_arch/features/data/models/user_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeUserModel extends _i1.Fake implements _i2.UserModel {}

/// A class which mocks [DoLoginDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoLoginDataSource extends _i1.Mock implements _i3.DoLoginDataSource {
  MockDoLoginDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> doLogin({String? email, String? password}) => (super
      .noSuchMethod(
          Invocation.method(#doLogin, [], {#email: email, #password: password}),
          returnValue: Future<_i2.UserModel>.value(_FakeUserModel())) as _i4
      .Future<_i2.UserModel>);
}
