// Mocks generated by Mockito 5.0.11 from annotations
// in flutter_clean_arch/test/feature/auth/domain/usecases/do_login_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_clean_arch/core/error/failure.dart' as _i5;
import 'package:flutter_clean_arch/features/domain/entities/user.dart' as _i6;
import 'package:flutter_clean_arch/features/domain/repositories/do_login_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [DoLoginRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoLoginRepository extends _i1.Mock implements _i3.DoLoginRepository {
  MockDoLoginRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.User>> doLogin(
          {String? email, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(#doLogin, [], {#email: email, #password: password}),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.User>>.value(
              _FakeEither<_i5.Failure, _i6.User>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.User>>);
}
